### PR TITLE
Bug fixes and output formatting

### PR DESCRIPTION
**Pull request by nitsanw**
Hi,
This is a bit of a mixed bag, so feel free to cherry pick the bits you find most relevant.
The most important aspects are:
1. Fix a bug in the inlined address range computation where the range was assigned to the wrong method.
2. Error handling for JVMTI calls (only in method signature, the same pattern needs applying to all JVMTI interactions).

In addition I added some comments, renamed variables for clarity (I think), and added a more compact format for inlined methods printing.
Happy to have a discussion to make the PR more palatable. I would like to improve formatting further and settle on good way to configure it, but not sure how important backwards compatibility is.
Thanks,
Nitsan

### CODE REVIEW

**Comment by jrudolph** [comment]
Thanks, @nitsanw. I'll have a look in the next few days.

**Comment by nitsanw** [comment]
Hi @jrudolph,
I understand you are probably busy and I realize this is not the cleanest PR. Is there anything I can do to help the review process along?
I would like to invest more time in this project and build further on the above changes to make PMA more robust.
Thanks,
Nitsan

**Comment by nitsanw** [comment]
ping?

**Comment by jrudolph** [comment]
@nitsanw, thanks again. I like many of your suggestions but I think we need to break them down a bit more to see better what's going on. Unfortunately, there was another PR open which contained similar cleanups as yours to `sig_string`, so that your changes won't apply any more.

Let's have those changes:
 * fix address range computations (I'd like to understand what was wrong in the first place)
 * change method delimiter (no need to make it configurable from my side)
 * introduce bool
 * discuss compact_inline_format

Could you open separate issues / PRs for those items, especially for the first item?

To give a few general guidelines about this project:
 * I'd like to keep the C-code as simple as possible. In the future, it's more likely that I will let the C-code generate a machine readable output which will be post-processed in another step written in another language more suitable for string manipulation than to litter the C-code with more (ad-hoc) formatting options that are hard to maintain and prone to bad bugs (segfaults in the target program).
 * To spare us all time spending on resolving conflicts it would make sense to announce and plan refactorings beforehand.
 * wrt to more error handling: with `sig_string` improved there's not much left. In theory, `(*vm)->GetEnv` could fail which would probably lead to segfaults but this is very unlikely to happen.

Anyway, thanks for sharing the wish to make perf-map-agent better!

**Comment by nitsanw** [comment]
I'll see if I can find the time to redo this PR as a series of smaller PRs. This is hard because all the changes sort of hit on the same file. Given the code is so small I hoped you'd go through the merge process.
I realize you have little time for reviews/maintenance, have you considered introducing more contributors to the project?

**Comment by jrudolph** [comment]
@nitsanw no worries, if you don't get to submitting the PR(s). If you don't I will at least fix the bug myself and see what to do about the other issues.

**Comment by jrudolph** [comment]
@nitsanw I added a few more changes similar to the ones you proposed. I didn't yet introduce compact_inline_format so if you'd like that feature please open a ticket to discuss it.

Thanks again. There was lots of good stuff in here.

Closing...

**Comment by nitsanw** [comment]
Glad you found it helpful. Will push further tweaks in near future.

**Pull request closed without merging**
